[package]
name = "tore-app"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
tore-sim = { path = "../tore-sim" }
cpal = "0.16"
tore-formats = { path = "../tore-formats" }
pollster = "0.4"
wgpu = { version = "27.0.1", default-features = false, features = ["std", "parking_lot", "metal", "dx12", "vulkan", "gles", "wgsl"] }
winit = "0.30.12"

[lints]
workspace = true
